#include "timer.h"
//a.k.a servo controller

//general TIM2 interrupt enabler
//PA2 AT TIM2CH3, PA3 AS TIM2 CH4
void setTim2(void){
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;			//Enable the TIM2 clock source
	GPIOA->CRL &= ~GPIO_CRL_CNF0;
	GPIOA->CRL |= GPIO_CRL_CNF0_1;//SET CNF TO AFIO
	GPIOA->CRL |= GPIO_CRL_MODE0;//SET MODE TO OUTPUT 50MHZ	
	
	GPIOA->CRL &= ~GPIO_CRL_CNF3;
	GPIOA->CRL |= GPIO_CRL_CNF3_1;//SET CNF TO AFIO
	GPIOA->CRL |= GPIO_CRL_MODE3;//SET MODE TO OUTPUT 50MHZ
	
	TIM2->CR1 |=TIM_CR1_DIR| TIM_CR1_ARPE;
	
	TIM2->CCER  |= TIM_CCER_CC1E;//ONE OUTPUT CAPTURE
	TIM2->CCMR1 |= TIM_CCMR1_OC1M_1|TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1PE;

	
	TIM2->CCER  |= TIM_CCER_CC4E;
	TIM2->CCMR2 |= TIM_CCMR2_OC4M_1| TIM_CCMR2_OC4M_2| TIM_CCMR2_OC4PE;

	
	TIM2->PSC	= 240;
	TIM2->ARR = 2000;//->50HZ
	
//	TIM2->CCR1 = 200;
//	TIM2->CCR4 = 200;
//	TIM2->EGR |= TIM_EGR_UG;
	TIM2->SR = 0x00000000;			//Clear Flag
}

///TIM3 SETUP
//PC6 AS TIM3 CH1, PC7 AS TIM3 CH2, PC8 AS TIM3 CH3, PC9 AS TIM3 CH4
//Note that, all channel in tim3 will share same PSC and ARR
//and others configuration
//Have to turn off LED blue and LED green on the board
void setTim3(void){
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	GPIOC->CRL &= ~GPIO_CRL_CNF6;
	GPIOC->CRL |= GPIO_CRL_CNF6_1;//SET CNF TO AFIO
	GPIOC->CRL |= GPIO_CRL_MODE6;//SET MODE TO OUTPUT 50MHZ
	
	GPIOC->CRL &= ~GPIO_CRL_CNF7;
	GPIOC->CRL |= GPIO_CRL_CNF7_1;//SET CNF TO AFIO
	GPIOC->CRL |= GPIO_CRL_MODE7;//SET MODE TO OUTPUT 50MHZ
	
	GPIOC->CRH &= ~GPIO_CRH_CNF8;
	GPIOC->CRH |= GPIO_CRH_CNF8_1;//SET CNF TO AFIO
	GPIOC->CRH |= GPIO_CRH_MODE8;//SET MODE TO OUTPUT 50MHZ
	
	GPIOC->CRH &= ~GPIO_CRH_CNF9;
	GPIOC->CRH |= GPIO_CRH_CNF9_1;//SET CNF TO AFIO
	GPIOC->CRH |= GPIO_CRH_MODE9;//SET MODE TO OUTPUT 50MHZ		

	TIM3->CR1    |=TIM_CR1_DIR| TIM_CR1_ARPE;	//set CR1 ARPE DIR AND CEN
	
	TIM3->CCER	 |= TIM_CCER_CC1E;													//set CC1E ENABLE
	TIM3->CCMR1  |= TIM_CCMR1_OC1PE | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2;//0x6800;			//set OC1M AND OC1PE
	
	TIM3->CCER	 |= TIM_CCER_CC2E;													//set CC1E ENABLE
	TIM3->CCMR1  |= TIM_CCMR1_OC2PE | TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_2;//0x6800;			//set OC1M AND OC1PE
	
	TIM3->CCER	 |= TIM_CCER_CC3E;													//set CC1E ENABLE
	TIM3->CCMR2  |= TIM_CCMR2_OC3PE | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2;//0x6800;			//set OC1M AND OC1PE

	TIM3->CCER	 |= TIM_CCER_CC4E;													//set CC1E ENABLE
	TIM3->CCMR2  |= TIM_CCMR2_OC4PE | TIM_CCMR2_OC4M_1 | TIM_CCMR2_OC4M_2;//0x6800;			//set OC1M AND OC1PE
	
	TIM3->CR1 |= TIM_CR1_CEN;
	TIM3->PSC     = 240;				//set PSC to 1000Hz
	TIM3->ARR     = 2000;			 //set ARR TO 100Hz
	TIM3->CCR1 = 200;
	TIM3->CCR2 = 150;
	TIM3->CCR3 = 100;
	TIM3->CCR4 = 50;
	TIM3->SR = 0x00000000;			//Clear Flag
}

//SET PB 6,7,8,9 AS TIM4 CH 1,2,3,4
void setTim4(void){
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;//Enable timer 3 for pwm
	GPIOB->CRL &= ~GPIO_CRL_CNF6;
	GPIOB->CRL |= GPIO_CRL_CNF6_1;//SET CNF TO AFIO
	GPIOB->CRL |= GPIO_CRL_MODE6;//SET MODE TO OUTPUT 50MHZ
	
	GPIOB->CRL &= ~GPIO_CRL_CNF7;
	GPIOB->CRL |= GPIO_CRL_CNF7_1;//SET CNF TO AFIO
	GPIOB->CRL |= GPIO_CRL_MODE7;//SET MODE TO OUTPUT 50MHZ
	
	GPIOB->CRH &= ~GPIO_CRH_CNF8;
	GPIOB->CRH |= GPIO_CRH_CNF8_1;//SET CNF TO AFIO
	GPIOB->CRH |= GPIO_CRH_MODE8;//SET MODE TO OUTPUT 50MHZ
	
	GPIOB->CRH &= ~GPIO_CRH_CNF9;
	GPIOB->CRH |= GPIO_CRH_CNF9_1;//SET CNF TO AFIO
	GPIOB->CRH |= GPIO_CRH_MODE9;//SET MODE TO OUTPUT 50MHZ		


	TIM4->CR1    |= TIM_CR1_DIR| TIM_CR1_ARPE;
	
	TIM4->CCER	 |= TIM_CCER_CC1E;													
	TIM4->CCMR1  |= TIM_CCMR1_OC1PE | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2;
	
	TIM4->CCER	 |= TIM_CCER_CC2E;													
	TIM4->CCMR1  |= TIM_CCMR1_OC2PE | TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_2;
	
	TIM4->CCER	 |= TIM_CCER_CC3E;													
	TIM4->CCMR2  |= TIM_CCMR2_OC3PE | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2;

	TIM4->CCER	 |= TIM_CCER_CC4E;													
	TIM4->CCMR2  |= TIM_CCMR2_OC4PE | TIM_CCMR2_OC4M_1 | TIM_CCMR2_OC4M_2;
	

	TIM4->PSC     = 240;				
	TIM4->ARR     = 2000;			 


	TIM4->SR = 0x00000000;			
}

void closeAllTimer(void){
	TIM2->CR1 &= ~TIM_CR1_CEN;
	TIM3->CR1 &= ~TIM_CR1_CEN;
	TIM4->CR1 &= ~TIM_CR1_CEN;
}
//void TIM2_IRQHandler(void){
//		greenLed_off();
//		indicator_on();
//		delay_ms(1200);
//		indicator_off();
//		greenLed_on();
//		TIM2->SR = 0x00000000;			//Clear Flag
//}
